### GET senders information
GET http://localhost:8080/api/v1/customers/senders

### GET recipients informatiom
GET http://localhost:8080/api/v1/customers/recipients

### Gat package information
GET http://localhost:8080/api/v1/customers/packages